stages:
  download_data:
    cmd: 'mkdir -p .data && wget http://data.statmt.org/news-commentary/v14/training/news-commentary-v14.en-ru.tsv.gz
      --output-document=.data/news-commentary-v14.en-ru.tsv.gz '
    outs:
    - .data/news-commentary-v14.en-ru.tsv.gz
  extract_data:
    cmd: gunzip -c .data/news-commentary-v14.en-ru.tsv.gz > .data/news-commentary-v14.en-ru.tsv
    deps:
    - .data/news-commentary-v14.en-ru.tsv.gz
    outs:
    - .data/news-commentary-v14.en-ru.tsv
  src_trg_split_dataset:
    cmd: python datamodules/split_data.py --file .data/news-commentary-v14.en-ru.tsv
      --src-out-file .data/SRC_news-commentary-v14.en-ru.tsv --trg-out-file .data/TRG_news-commentary-v14.en-ru.tsv
    deps:
    - .data/news-commentary-v14.en-ru.tsv
    outs:
    - .data/SRC_news-commentary-v14.en-ru.tsv
    - .data/TRG_news-commentary-v14.en-ru.tsv
