stages:
  download_data:
    cmd: 'mkdir -p .data && wget http://data.statmt.org/news-commentary/v14/training/news-commentary-v14.en-ru.tsv.gz
      --output-document=.data/news-commentary-v14.en-ru.tsv.gz '
    outs:
    - .data/news-commentary-v14.en-ru.tsv.gz
  extract_data:
    cmd: gunzip -c .data/news-commentary-v14.en-ru.tsv.gz > .data/news-commentary-v14.en-ru.tsv
    deps:
    - .data/news-commentary-v14.en-ru.tsv.gz
    outs:
    - .data/news-commentary-v14.en-ru.tsv
