stages:
  download_data:
    cmd: 'mkdir -p .data && wget http://data.statmt.org/news-commentary/v14/training/news-commentary-v14.en-ru.tsv.gz
      --output-document=.data/news-commentary-v14.en-ru.tsv.gz '
    outs:
    - .data/news-commentary-v14.en-ru.tsv.gz
  extract_data:
    cmd: gunzip -c .data/news-commentary-v14.en-ru.tsv.gz > .data/news-commentary-v14.en-ru.tsv
    deps:
    - .data/news-commentary-v14.en-ru.tsv.gz
    outs:
    - .data/news-commentary-v14.en-ru.tsv
  src_trg_split_dataset:
    cmd: python datamodules/split_data.py --file .data/news-commentary-v14.en-ru.tsv
      --src-out-file .data/SRC_news-commentary-v14.en-ru.tsv --trg-out-file .data/TRG_news-commentary-v14.en-ru.tsv
    deps:
    - .data/news-commentary-v14.en-ru.tsv
    outs:
    - .data/SRC_news-commentary-v14.en-ru.tsv
    - .data/TRG_news-commentary-v14.en-ru.tsv
  build_bpe_src:
    cmd: yttm bpe --data .data/SRC_news-commentary-v14.en-ru.tsv --model .data/SRC_news-commentary-v14.en-ru.yttm
      --vocab_size 10000
  build_bpe_trg:
    cmd: yttm bpe --data .data/TRG_news-commentary-v14.en-ru.tsv --model .data/TRG_news-commentary-v14.en-ru.yttm
      --vocab_size 10000
  bpe_encode_src:
    cmd: yttm encode --output_type id --model .data/SRC_news-commentary-v14.en-ru.yttm
      --stream < .data/SRC_news-commentary-v14.en-ru.tsv > .data/SRC_BPE_ENCODED_news-commentary-v14.en-ru.tsv
    deps:
    - .data/SRC_news-commentary-v14.en-ru.tsv
    - .data/SRC_news-commentary-v14.en-ru.yttm
    outs:
    - .data/SRC_BPE_ENCODED_news-commentary-v14.en-ru.tsv
  bpe_encode_trg:
    cmd: yttm encode --output_type id --model .data/TRG_news-commentary-v14.en-ru.yttm
      --stream < .data/TRG_news-commentary-v14.en-ru.tsv > .data/TRG_BPE_ENCODED_news-commentary-v14.en-ru.tsv
    deps:
    - .data/TRG_news-commentary-v14.en-ru.tsv
    - .data/TRG_news-commentary-v14.en-ru.yttm
    outs:
    - .data/TRG_BPE_ENCODED_news-commentary-v14.en-ru.tsv
