on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install deps
        run: |
          pip install pytest pytorch-lightning torch pytorch-nlp --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: run tests
        run: |
          PYTHONPATH=. pytest -sv ./